return {}
-- return {
--   'zbirenbaum/copilot.lua',
--   opts = {
--     suggestion = {
--       auto_trigger = false,
--       keymap = {
--         accept = '<tab>',
--       },
--     },
--   },
-- }
