return {}
-- return {
--   "CopilotC-Nvim/CopilotChat.nvim",
--   opts = {
--     model = "claude-3.5-sonnet",
--     mappings = {
--       reset = {
--         normal = "<C-q>",
--         insert = "<C-q>",
--       },
--     },
--   },
-- }
